name: mock_api
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.9.2
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  skeletonizer: ^2.1.0+1
  flutter_svg: ^2.2.1
  cached_network_image: ^3.4.1
  dio: ^5.9.0
  hive_flutter: ^1.1.0
  equatable: ^2.0.7
  dartz: ^0.10.1
  get_it: ^8.2.0
  requests_inspector: ^5.1.1
  internet_connection_checker: ^3.0.1
  flutter_bloc: ^9.1.1
  flutter_secure_storage: ^9.2.4
  modal_progress_hud_nsn: ^0.5.1
  pretty_dio_logger: ^1.4.0
  injectable: ^2.5.2
  easy_localization: ^3.0.8

dev_dependencies:
  flutter_pre_commit: ^0.2.4
  build_runner:
  injectable_generator: 
  hive_generator: 
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/translations/
    - assets/svgs/
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-Light.ttf
          weight: 300
        - asset: assets/fonts/Cairo-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Cairo-Black.ttf
          weight: 900    
  
flutter_assets:
  assets_path: assets/
  output_path: lib/generated/
  filename: app_assets.dart
  ignore_comments: true
  field_prefix: 
  classname: AppAssets
